DROP TABLE IF EXISTS ValueBool;
DROP TABLE IF EXISTS ValueNumber;
DROP TABLE IF EXISTS ValueString;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS Session;

CREATE TABLE Session (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    SessionStart TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Event (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  SessionId INTEGER NOT NULL ,
  TimeStamp INTEGER NOT NULL,
  Key TEXT NOT NULL,
  Type TEXT NOT NULL,

  FOREIGN KEY (SessionId) REFERENCES Session(Id)
);

CREATE TABLE ValueBool (
  Id INTEGER PRIMARY KEY,
  Value BOOLEAN NOT NULL CHECK (Value IN (0,1)),
  FOREIGN KEY (Id) REFERENCES Event(Id)
);

CREATE TABLE ValueString(
  Id INTEGER PRIMARY KEY,
  Value TEXT NOT NULL,
  FOREIGN KEY (Id) REFERENCES Event(Id)
);

CREATE TABLE ValueNumber(
  Id INTEGER PRIMARY KEY,
  Value REAL NOT NULL,
  FOREIGN KEY (Id) REFERENCES Event(Id)
);

-- INSERT INTO Event(Name, Type) VALUES ("/foo", "String");
-- INSERT INTO [Session] DEFAULT VALUES;