!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers: []
mAnalogIn: []
mAnalogOut: []
mDefaultI2CWrappers: {}
mDigitalIO: []
mEncoders: []
mGyros: []
mPwm: []
mRelays: []
mSimulatorComponents: []
mSolenoids: []
