subsystems:
  drive:
    implemented: false
    talons:
      front_left_steer:  23
      front_right_steer: 22
      back_left_steer:   21
      back_right_steer:  20
    talonSRs:
      front_left_drive:  3
      front_right_drive: 2
      back_left_drive:   1
      back_right_drive:  0

    constants:
      steer_kp: 11
      steer_ki: 0
      steer_kd: 1

      # No Idea if these are correct
      front_left_id:  0
      front_right_id: 1
      back_left_id:   2
      back_right_id:  3


  canifier:
    implemented: false
    constants:
      canId: 12

constants:
  wheelbase_length: 30
  track_width: 30